package DSA;
/*
 *  
 * OUTLINE
 * (A)  DISCUSSIONS AND EXAMPLES ABOUT SINGLY & DOUBLY LINKED LISTS
 *      1.WHAT IS A LINKED LIST?
 *          A LINKED LIST IS A SEQUENTIAL LIST OF NODES THAT HOLD DATA WHICH POINT TO OTHER NODES ALSO CONTAINING DATA.
 *      2.WHERE ARE LINKED LISTS USED?
 *          -> USED IN MANY List, Queue & Stack IMPLEMENTATIONS.
 *          -> GREAT FOR CREATING CIRCULAR LISTS.
 *          -> CAN EASILY MODEL REAL WORLD OBJECTS SUCH AS TRAINS.
 *          -> USED IN SEPERATE CHAINING, WHICH IS PRESENT CERTAIN Hashtable IMPLEMENTATIONS TO DEAL WITH HASHING COLLISIONS.
 *          -> OFTEN USED IN THE IMPLEMENTATIONS OF ADJACENCY LISTS FOR GRAPHS.
 *      3.TERMINOLOGY
 * 
 *      4.SINGLY LINKED vs. DOUBLY LINKED LIST
 * (B)  IMPLEMENTATION DETAILS
 *      1.HOW TO INSERT NEW ELEMENTS
 *      2.HOW TO REMOVE ELEMENTS
 * (C) CPMPLEXITY ANALYSIS
 * 
 */
public class linkedLists {
    public static void main(String[] args) {
        
    }
}
